### ISSUE TITLE
Add back button to webview in iOS

### ISSUE THREAD

**Issue by funnygerman** [Earlybyte/aad_oauth#56] opened 2020-07-23 13:17 UTC
Currently there is no back button in the login webview screen in iOS.

That means the user can't cancel login process

**Comment by funnygerman** [comment] 2020-07-30 07:59
And also noticed, back  buttom on Android doesn't work too

**Comment by sladomic** [comment] 2020-07-31 08:15
duplicate of #43

**Closed by sladomic** 2020-07-31 08:15 UTC

**Comment by funnygerman** [comment] 2020-07-31 13:13
But it's not really a duplicate? And there were not really a solution?

**Comment by msarkrish** [comment] 2021-08-25 15:47
@funnygerman Did you find any solution?

@sladomic After using login method from oauth, android default back button is not working.
How to solve this error

I/art     (16059): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/Vi
ew$OnUnhandledKeyEventListener;
I/art     (16059):   at boolean androidx.core.view.ViewCompat.dispatchUnhandledKeyEventBeforeHierarchy(android.view.View, android.view.KeyEvent) (ViewCompat.java:3871)
I/art     (16059):   at boolean androidx.core.view.KeyEventDispatcher.dispatchBeforeHierarchy(android.view.View, android.view.KeyEvent) (KeyEventDispatcher.java:63)
I/art     (16059):   at boolean androidx.core.app.ComponentActivity.dispatchKeyEvent(android.view.KeyEvent) (ComponentActivity.java:137)
I/art     (16059):   at boolean com.android.internal.policy.DecorView.dispatchKeyEvent(android.view.KeyEvent) (DecorView.java:320)
I/art     (16059):   at int android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4384)
I/art     (16059):   at int android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4355)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3899)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3952)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3918)
I/art     (16059):   at void android.view.ViewRootImpl$AsyncInputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4045)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:3926)
I/art     (16059):   at void android.view.ViewRootImpl$AsyncInputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:4102)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3899)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3952)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3918)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:3926)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3899)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3952)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3918)
I/art     (16059):   at void android.view.ViewRootImpl$AsyncInputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4078)
I/art     (16059):   at void android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(java.lang.Object, boolean) (ViewRootImpl.java:4246)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager$PendingEvent.run() (InputMethodManager.java:2397)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(android.view.inputmethod.InputMethodManager$PendingEvent, boolean) (InputMetho
dManager.java:1993)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager.finishedInputEvent(int, boolean, boolean) (InputMethodManager.java:1984)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(int, boolean) (InputMethodManager.java:2374)
I/art     (16059):   at void android.view.InputEventSender.dispatchInputEventFinished(int, boolean) (InputEventSender.java:141)
I/art     (16059):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/art     (16059):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:329)
I/art     (16059):   at void android.os.Looper.loop() (Looper.java:142)
I/art     (16059):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6375)
I/art     (16059):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (16059):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:912)
I/art     (16059):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:802)
I/art     (16059): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.sar.inci
dent-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sar.incident-2/lib/arm64, /data/app/com.sar.incident-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
I/art     (16059):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:74)
I/art     (16059):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     (16059):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     (16059):   at boolean androidx.core.view.ViewCompat.dispatchUnhandledKeyEventBeforeHierarchy(android.view.View, android.view.KeyEvent) (ViewCompat.java:3871)
I/art     (16059):   at boolean androidx.core.view.KeyEventDispatcher.dispatchBeforeHierarchy(android.view.View, android.view.KeyEvent) (KeyEventDispatcher.java:63)
I/art     (16059):   at boolean androidx.core.app.ComponentActivity.dispatchKeyEvent(android.view.KeyEvent) (ComponentActivity.java:137)
I/art     (16059):   at boolean com.android.internal.policy.DecorView.dispatchKeyEvent(android.view.KeyEvent) (DecorView.java:320)
I/art     (16059):   at int android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4384)
I/art     (16059):   at int android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4355)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3899)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3952)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3918)
I/art     (16059):   at void android.view.ViewRootImpl$AsyncInputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4045)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:3926)
I/art     (16059):   at void android.view.ViewRootImpl$AsyncInputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:4102)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3899)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3952)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3918)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:3926)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3899)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3952)
I/art     (16059):   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:3918)
I/art     (16059):   at void android.view.ViewRootImpl$AsyncInputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:4078)
I/art     (16059):   at void android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(java.lang.Object, boolean) (ViewRootImpl.java:4246)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager$PendingEvent.run() (InputMethodManager.java:2397)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(android.view.inputmethod.InputMethodManager$PendingEvent, boolean) (InputMetho
dManager.java:1993)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager.finishedInputEvent(int, boolean, boolean) (InputMethodManager.java:1984)
I/art     (16059):   at void android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(int, boolean) (InputMethodManager.java:2374)
I/art     (16059):   at void android.view.InputEventSender.dispatchInputEventFinished(int, boolean) (InputEventSender.java:141)
I/art     (16059):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/art     (16059):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:329)
I/art     (16059):   at void android.os.Looper.loop() (Looper.java:142)
I/art     (16059):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6375)
I/art     (16059):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (16059):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:912)
I/art     (16059):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:802)
I/art     (16059)
